export default function TermsOfService() {
  return (
    <main className="flex min-h-screen flex-col px-6 py-12">
      <div className="mx-auto max-w-3xl">
        <h1 className="text-3xl font-bold tracking-tight text-black">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: August 2026</p>
        <div className="mt-8 space-y-6 text-zinc-600">
          <div>
            <h2 className="text-xl font-semibold text-black">1. Acceptance of Terms</h2>
            <p className="mt-2 leading-relaxed">
              By accessing and using the Look AI website and its services
              (&quot;Service&quot;), you accept and agree to be bound by the terms
              and conditions of this Agreement. If you do not agree with any of
              the terms of this Agreement, you may not access the Service.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">2. Description of Service</h2>
            <p className="mt-2 leading-relaxed">
              Look AI is an AI-powered styling assistant that helps users find
              their perfect look in seconds. The Service provides personalized
              fashion and styling recommendations based on user preferences,
              inputs, and AI-generated analysis. All recommendations are for
              informational and entertainment purposes only.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">3. User Account</h2>
            <p className="mt-2 leading-relaxed">
              You may be required to create an account to access certain
              features of the Service. You are responsible for maintaining the
              confidentiality of your account credentials and for all activities
              that occur under your account. You agree to notify us immediately
              of any unauthorized use of your account.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">4. User Content and Conduct</h2>
            <p className="mt-2 leading-relaxed">
              You are solely responsible for any content, feedback, ratings,
              reviews, or other materials you submit, post, or display through
              the Service. You agree not to use the Service to post or transmit
              any unlawful, harmful, threatening, abusive, defamatory, or
              otherwise objectionable content. You further agree not to use the
              Service to impersonate any person or entity, or to falsely state
              or otherwise misrepresent your affiliation with any person or
              entity.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">5. AI Recommendations — Disclaimer</h2>
            <p className="mt-2 leading-relaxed">
              The styling suggestions, outfit recommendations, and fashion
              advice generated by Look AI are based on artificial intelligence
              models and algorithmic analysis. While we strive to provide useful
              and accurate recommendations, we do not guarantee that any
              recommendation will suit your body type, personal style, budget, or
              local availability. You should exercise your own judgment before
              making any purchase or styling decision based on our suggestions.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">6. Third-Party Links and Products</h2>
            <p className="mt-2 leading-relaxed">
              The Service may contain links to third-party websites, products,
              or services, including online stores and fashion retailers. These
              links are provided for your convenience only. We do not control and
              are not responsible for the content, privacy policies, terms of
              service, or practices of any third-party websites or services. Your
              interaction with any third-party website or service is at your own
              risk and subject to that third party&apos;s own terms and conditions.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">7. Intellectual Property</h2>
            <p className="mt-2 leading-relaxed">
              The Service, including its original content, features, algorithms,
              design, and branding, is owned by Look AI and is protected by
              international intellectual property laws. You may not reproduce,
              distribute, modify, create derivative works of, publicly display,
              or commercially exploit any part of the Service without our prior
              written permission.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">8. Limitation of Liability</h2>
            <p className="mt-2 leading-relaxed">
              To the fullest extent permitted by applicable law, Look AI shall
              not be liable for any indirect, incidental, special, consequential,
              or punitive damages, or any loss of profits or revenues, whether
              incurred directly or indirectly, or any loss of data, use, goodwill,
              or other intangible losses resulting from your access to or use of
              or inability to access or use the Service.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">9. Termination</h2>
            <p className="mt-2 leading-relaxed">
              We reserve the right, at our sole discretion, to terminate or
              suspend your access to the Service immediately, without prior notice
              or liability, for any reason whatsoever, including without limitation
              if you breach these Terms. Upon termination, your right to use the
              Service will immediately cease.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">10. Changes to These Terms</h2>
            <p className="mt-2 leading-relaxed">
              We reserve the right, at our sole discretion, to modify or replace
              these Terms at any time. If a revision is material, we will provide
              at least 30 days&apos; notice before any new terms take effect. What
              constitutes a material change will be determined at our sole
              discretion.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">11. Governing Law</h2>
            <p className="mt-2 leading-relaxed">
              These Terms shall be governed by and construed in accordance with
              the laws of Pakistan, without regard to its conflict of law
              provisions. Any legal action or proceeding arising under these Terms
              will be brought exclusively in the courts located within Pakistan.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-black">12. Contact Us</h2>
            <p className="mt-2 leading-relaxed">
              If you have any questions about these Terms of Service, please
              contact us at{" "}
              <a
                href="mailto:support@lookai.app"
                className="text-black underline hover:text-zinc-800"
              >
                support@lookai.app
              </a>
              .
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
